### ISSUE TITLE
`logout` cannot be resolved or is not a method of `io.quarkiverse.renarde.oidc.impl.RenardeSecurityController`

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/intellij-quarkus#1068]
In https://github.com/ia3andy/quarkus-blast/blob/main/src/main/resources/templates/tags/user.html#L12, a validation error is shown  
> `logout` cannot be resolved or is not a method of `io.quarkiverse.renarde.oidc.impl.RenardeSecurityController`

The reason is there are 2 `RenardeSecurityController` implementations, from `io.quarkiverse.renarde.oidc.impl` and `io.quarkiverse.renarde.security.impl`,  validation picks the wrong one.

<img width="1785" alt="Screenshot 2023-08-01 at 16 28 59" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/c147a98b-3193-4522-a65b-fd9c93401bcd">

@FroMage @ia3andy @mkouba how is that even supposed to work in Qute?

**Comment by mkouba** [comment]
> @FroMage @ia3andy @mkouba how is that even supposed to work in Qute?

I have no idea how Renarde handles this particular output expression. @FroMage is there a template extension method that handles the `uri:` namespace?

**Comment by ia3andy** [comment]
@mkouba https://github.com/quarkiverse/quarkus-renarde/blob/main/runtime/src/main/java/io/quarkiverse/renarde/util/QuteResolvers.java

**Comment by angelozerr** [comment]
Indeed and I have seen it supports the `m` uri for messages https://github.com/quarkiverse/quarkus-renarde/blob/c18e6e070ea9eae6d4a7959c51e8e690494adf25/runtime/src/main/java/io/quarkiverse/renarde/util/QuteResolvers.java#L116 which is so many used in https://github.com/FroMage/RivieraDEV-Quarkus/blob/26e915c11a38f52d2eea760c0a545db7ecf2bd24/src/main/resources/templates/Application/access.html#L7

We have started a support for [Type-safe Message Bundles](https://github.com/redhat-developer/quarkus-ls/pull/845#top):

You can have completion, jump to definition in Qute template:

![QuteMessage1](https://github.com/redhat-developer/intellij-quarkus/assets/1932211/6ff9a26f-2f4e-48e0-a3de-946c0c00c6fa)

and you can see as inlay hint the message:

![image](https://github.com/redhat-developer/intellij-quarkus/assets/1932211/fd4d3aa3-0387-43da-be0b-d2438e876e45)

I wonder if we should support this `m` uri message to have a nice message support for renarde because today I think it can a nightmare when your application uses so many messages (like [the ](https://github.com/FroMage/RivieraDEV-Quarkus))

@FroMage have you the intentionto move your support in Qute? @mkouba do you think it can be a good idea?

Before starting this support I would like to know if it is stable or not.

**Comment by FroMage** [comment]
It is stable, but kinda hackish.

**Comment by FroMage** [comment]
> how is that even supposed to work in Qute?

Well… to be honest… probably, by accident 😂

I should rename one of those classes, for sure.

**Comment by FroMage** [comment]
https://github.com/quarkiverse/quarkus-renarde/issues/155

**Comment by fbricon** [comment]
https://github.com/quarkiverse/quarkus-renarde/issues/155 being closed and quarkus-blast being up to date, the error is no longer present. With Qute/Renarde resolving ambiguous classes likely a fluke, I'm closing this one.
