### ISSUE TITLE
`@BuildStep`s in an extension processor are considered unused methods 

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#1095]
`@BuildStep`s in an extension processor are considered unused methods in IJ, which is not true

_Originally posted by @gastaldi in https://github.com/redhat-developer/intellij-quarkus/issues/1094#issuecomment-1672024387_

**Comment by gastaldi** [comment]
The plugin should only mark the method as unused if it's not reachable by the Quarkus build processor

**Comment by fbricon** [comment]
@gastaldi do you have a small project example of `@BuildStep` usage?
How do we know if the annotated method is "not reachable by the Quarkus build processor"?

**Comment by fbricon** [comment]
Making methods annotated with `@BuildStep` show as used is easy

However,  running a build as part of the validation, to check if it's found in a dot file is probably not gonna happen. 
- it requires applying building the project 1st, the applying it on a test project 
- it might take an unreasonably long time

**Comment by gastaldi** [comment]
> Making methods annotated with `@BuildStep` show as used is easy

I think that's a good start. 

> However, running a build as part of the validation, to check if it's found in a dot file is probably not gonna happen.
> 
> * it requires building the project 1st, then applying it on a test project
> * it might take an unreasonably long time

I agree, and I am not sure what would be the best solution here. Maybe @dmlloyd has any idea?

**Comment by dmlloyd** [comment]
I'm late on this (PTO) but `@BuildStep` should *always* be considered used.

Build step methods are contextually part of an extension's deployment module. The deployment module is independent of any particular application. The steps actually used for an application are dependent on the extensions present, the configuration of the application, and the application's content. A build step method may validly rely on an extension that isn't even present for some applications. Since an extension is usable for many applications, it doesn't make sense to make assumptions about the use of a given build step method based on a single application, thus build steps should always be considered used unless it can be proven *locally within the extension itself* that the step can never run.

**Comment by dmlloyd** [comment]
Not offhand, but if I think of any I'll mention them.
