### ISSUE TITLE
Add the qj code snippet

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-quarkus#12]
Add a code snippet for configuring a Jaeger tracer in application.properties

**Comment by angelozerr** [comment]
@jeffmaury please note that we would like to support snippet on MicroProfile LS  side. I think it's better to do that because:

 * we can show Jaeger snippet only if quarkus-jaeger extension is present in the project.
 * all LSP client (vscode, Eclipse IDE, IJ) will benefit with snippet without extra effort

See https://github.com/redhat-developer/vscode-quarkus/issues/119#issuecomment-545884088

**Comment by jeffmaury** [comment]
Fixed in 1.0.0
