### ISSUE TITLE
Excessive background tasks that never finish and kill my system

### ISSUE THREAD

**Issue by stephenc** [redhat-developer/intellij-quarkus#239]
Twice now I have had my system drown in CPU usage due to 3.5k+ tasks like:

![Screenshot 2020-09-21 at 15 39 08](https://user-images.githubusercontent.com/209336/93788935-21d9c500-fc29-11ea-9ce3-7ca9a63b6241.png)

A thread dump revealed all these were:

```
Name: ApplicationImpl pooled thread 2213
State: TIMED_WAITING
Total blocked: 0  Total waited: 1,881

Stack trace: 
jdk.internal.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:357)
com.intellij.openapi.project.DumbServiceImpl.waitForSmartMode(DumbServiceImpl.java:401)
com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:139)
com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:103)
com.redhat.devtools.intellij.quarkus.search.ProjectLabelManager.getProjectLabelInfo(ProjectLabelManager.java:80)
com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$getJavaProjectlabels$6(QuarkusLanguageClient.java:125)
com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient$$Lambda$2067/0x0000000801753840.get(Unknown Source)
com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient$1.run(QuarkusLanguageClient.java:94)
com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1491/0x0000000801384c40.apply(Unknown Source)
com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
com.intellij.openapi.progress.impl.ProgressRunner$$Lambda$1172/0x000000080106a040.run(Unknown Source)
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$399/0x00000008004ec840.run(Unknown Source)
com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
com.intellij.openapi.progress.impl.ProgressRunner$$Lambda$1168/0x0000000801069040.get(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
java.security.AccessController.doPrivileged(Native Method)
java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
java.lang.Thread.run(Thread.java:834)
```

While normally I would appreciate the office heating, given the sun is beaming in my office window and I'm already baking the extra CPU space heater effect is not something I am happy with right now

**Comment by jeffmaury** [comment]
Do you really have 3.5K tasks like this ? There should be 1 per opened Java file in your project. No big change here, just the computation of project labels is done as a background task so it now appears in the status bar (in order to fix #223)

**Comment by stephenc** [comment]
Yes my IDE dies when I have more than 2.5k of them... it can take another 1k before I can interrupt the IDE to restart it

**Comment by jeffmaury** [comment]
So you have 3,5k opened Java files or is there an explosion of those tasks relative to the number of opened Java files ?

**Comment by stephenc** [comment]
I have at most 15 tabs open. The tasks just start exploding and once they go over a threshold they take longer to clear before more get added... and once that happens it's just a ticking time Moby

**Comment by Temdegon** [comment]
I've faced the same issue. From time to time I have 1-2k of "Computing java project labels" tasks running. Once it happened on just hello-world app. Another time was when I've changed quarkus version in pom.xml (the project is really tiny). This process consumes all available CPU, freezes the system and burning down my laptop. 
It never ends (or at least I'm not patient enough to wait more than 5 minutes with the melting laptop on my knees). So I have to kill the intellij process and restart it. And somehow that helps, but not every time, so need to kill-restart multiple times... 
It's rather hard to figure out that it caused by quarkus plugin bcs it doesn't happen so often and I've faced it only after a weeks since plugin installation. I suspected another plugins, intellij update, configuration changes and spent quite some time to that issue. Also I have to admit it's not that easy to do configuration changes and plugins tweaks when the intellij is such busy. 
Googling by "Computing java project labels" doesn't help at all. I've manually found this ticket after figuring out the issue is with that plugin. So may be it makes sense to adjust the bug title specifying the task name. That would help others to find it from google and a bit slow the down the global heating this way.
