### ISSUE TITLE
Weird bug in the community edition plugin when editing any java code

### ISSUE THREAD

**Issue by Ulimn** [redhat-developer/intellij-quarkus#459]
I am using IntelliJ Community Edition and the Quarkus Tools plugin. 

Whenever I make any change in my code, in the status bar there is some kind of event/message saying "Computing Java diagnostics". When I type the code at regular speed, it is noticable, there are mini-hangs after each keystroke. 

Quarkus Tools and the necessary Red Hat Telemetry plugins are the only ones enabled.
I'm on MacOS on an M1 MacBook Air machine, latest Big Sur - if it matters. 

I attached a small video showing the problem:
https://user-images.githubusercontent.com/1268347/134785961-c50400c5-f455-43ec-8f96-ef14eaa94e5a.mov

What might be the issue here? Can I provide any more details?

**Comment by angelozerr** [comment]
We did a lot of improvement since this issue has been created. The only case which is slow is when you write a Java class with JAX-RS @Path annotation.

After some investigation, I noticed that it is the codelens URL support which is slow because it checks for each method that the server is started to show the codelens.

@fbricon I wonder if it is annoying to show codelens URL even if the server is not started. This check is not robust because when the server is started, it doesn't refresh codelens.

If you think it is very important to show codelens URL only when server is started, I think we should create a Thread as deamon which checks that server is enabled and when it is enabled, it refresh codelens. What do you think about that?

**Comment by fbricon** [comment]
mm the thread would have to do some regular polling. Can't you check the server is running once, at the beginning of tthe codelens request, then each method could just read the result without having to recompute?

**Comment by fbricon** [comment]
@angelozerr as for the initial issue (computing diagnotstics on keystroke), was debouncing introduced since that issue was opened? in which case we should close this one, and open a new one for the codelens problem

**Comment by angelozerr** [comment]
> Can't you check the server is running once, at the beginning of tthe codelens request, then each method could just read the result without having to recompute?

Indeed we could do that, but with IJ Quarkus, I tested just with one method (so it is the same thing if we test the server available on begining of the codelens request), and Java editor is very slow.

> @angelozerr as for the initial issue (computing diagnotstics on keystroke), was debouncing introduced since that issue was opened? in which case we should close this one, and open a new one for the codelens problem

Yes you are right, I will create a new issue. I close this issue since problem seems resolved. 

@Ulimn please reopen the issue if you have the problem again.
