### ISSUE TITLE
Add support for application.yaml

### ISSUE THREAD

**Issue by zeljkot** [redhat-developer/intellij-quarkus#50]
Property autocomplete works only for application.properties. Add support for application.yaml, too.

**Comment by angelozerr** [comment]
Is IJ gives the capability to manage a YAML editor? If yes, is it enable to set a JSON Schema file to the YAML editor for a given file URI? If it's possible, MicroProfile LS provides now a request which returns the JSON Schema for a given URI.

We use this feature in vscode (and soon in Eclipse IDE) with YAML Language Server.

**Comment by rainmanhhh** [comment]
idea supports check(and auto-complete) spring application.yml with json schema to, probably it can be used for quarkus

**Comment by rainmanhhh** [comment]
it seems vscode plugin not support yml either

**Comment by angelozerr** [comment]
> idea supports check(and auto-complete) spring application.yml with json schema, probably it can be used for quarkus

sts4 have a language server which parses YAML file. They have developed from scratch a YAML parser (fault tolerant parser).

> it seems vscode plugin not support yml either

vscode-quarkus supports application.yaml, but instead of managing parse of YAML and manages other features like validation for YAML, outline, highlight, completion based on YAML/JSON Schema,  vscode-quarkus delegates the YAML features (yaml parse, completion, hover, validation, etc) to vscode-yaml. 

The only work that vscode-quarkus does, is that it bind the application.yaml with a generated JSON Schema (according to the Quarkus/MP properties available for the project). vscode-yaml (which consumes the yaml language server) does the work by using the generated JSON Schema (validation, completion, etc). 

vscode-yaml manages very good YAML support (validation, completion, outline, etc), so by consuming it (just by giving a JSON Schema) was easy and we don't reinvent the wheel. More in Eclipse IDE, the yaml language server is consumed too (with WWD), so it will possible to do the same strategy than vscode.

**Comment by rainmanhhh** [comment]
idea can specific a json schema for yaml file(or url) manually. what url should I use?

**Comment by angelozerr** [comment]
I'm afraid that it will not so simple like this. In vscode, when application.yaml is opened, the yaml language server ask to the vscode-quarkus:

 * the URL of the JSON Schema to use for the yaml file (we use a custom schema prefix for that). See https://github.com/redhat-developer/vscode-quarkus/blob/a806144721b1057d4875fe91b13a32e13020e697/src/yaml/YamlSchema.ts#L167
 * the content of the JSON Schema. See https://github.com/redhat-developer/vscode-quarkus/blob/a806144721b1057d4875fe91b13a32e13020e697/src/yaml/YamlSchema.ts#L72

To retrieve the JSON Schema content, the LSP request `microprofile/jsonSchemaForProjectInfo` from MP language server is consumed.

I don't know how IJ is working but the idea is to develop an IJ extension for YAML which consumes the LSP request `microprofile/jsonSchemaForProjectInfo`

**Comment by rainmanhhh** [comment]
so IJ quarkus tools plugin doesn't provider a port to receive request and return url of JSON Schema/content of JSON Schema?

**Comment by angelozerr** [comment]
> so IJ quarkus tools plugin doesn't provider a port to receive request and return url of JSON Schema/content of JSON Schema?

I don't know, please ask to @jeffmaury

**Comment by jeffmaury** [comment]
Quarkus Tool does not support YAML format for application properties yet

**Comment by rainmanhhh** [comment]
I suggest make the plugin generate a json schema file into compile output dir (like spring-configuration-metadata.json generated by spring configuration annotation processor), so that user can view the schema directly or set it to IJ manually
