### ISSUE TITLE
Installing the Intellij plugin for Quarkus tools in breaking spring application.properties

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/intellij-quarkus#51]
reported originally at https://github.com/quarkusio/code.quarkus.io/issues/289 by @vinchauhan

**Describe the bug**
Quarkus Intellij plugin is making spring projects created from Intellij  start.spring.io plugin not working as application.properties is loosing autocompletion.

**Expected behavior**
Spring projects application.properties shouldnt be affected.
**Actual behavior**
The application.properties are loosing spring autocompletion as well as an lts folder is created on the root which application.properties_error.log

**To Reproduce**
1. Install the Quarkus tools from Intellij plugin website or IDE
2. Create a spring project from Intellij IDE using start.spring.io
3. The application.properties are loosing spring autocompletion as well as an lts folder is created on the root which application.properties_error.log

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Browser: 
 - OS: 

**Additional context**
(Add any other context about the problem here.)

**Comment by maxandersen** [comment]
yeah, I've expected this to happen when I noticed quarkus used the same name :/

@fbricon how do you guys handle this in vscode/eclipse ? 

can we do some detection to avoid the conflicts ?

**Comment by fbricon** [comment]
in vscode, application.properties will be recognized either as Spring Boot properties or Quarkus' (priority is undefined, AFAIK but in practice, I've seen Spring Boot win), and then the matching Language Server will kick in. User can then toggle the file type to the expected one, restoring expected behavior.

The problem everybody has, is how do you identify an quarkus project vs a spring boot project, when both use the same properties name (that was really a bad choice from Quarkus IMHO)? The surefire way to do it is to inspect the classpath, but that takes way too much time. Alternatively, you can inspect the build descriptors, but you can still inherit quarkus stuff from a parent pom for instance, and the project itself will make no direct references to quarkus.

So right now this is still an open issue on the vscode side (https://github.com/redhat-developer/vscode-quarkus/issues/45).

**Comment by maxandersen** [comment]
@fbricon how many of the IDE's supports lookahead on content type mapping to editor ? i believe eclipse does. could it look if 'quarkus' are the first characters - then you would be fairly certain it’s a quarkus driven properties file ?

**Comment by jeffmaury** [comment]
Then you're stuck with a fresh Quarkus application generated from code.quarkus.io as application.properties is empty !!!!.
What about what I've used in jbosstools-quarkus to search for `io.quarkus.runtime.LaunchMode` as the JDT index should be fast enough ?

**Comment by maxandersen** [comment]
Good point @jeffmaury - could be remedied by having a "quarkus...something" in that file or add ## Quarkus 
at top as a marker.

searching for `LaunchMode` is neat but does the various IDE allow you to somehow specifyt that *before* it acutally opens the editor ? 

at least in eclipse the content type detectors are declarative as in you can't or at least shouldn't execute code from the plugn as otherwise the whole plugin loads even if not used/needed/

**Comment by fbricon** [comment]
having a ## quarkus marker on the very 1st line would help. But then currently existing properties would not be detected properly

**Comment by maxandersen** [comment]
can't have all our cake and eat it too..or something ;)

**Comment by aguibert** [comment]
would it be too much for the plugin to do some light parsing of the application.properties file?

Many standard Quarkus properties start with `quarkus.*` and likewise for Spring properties with `spring.*`. It's not a perfect solution but I think it would work in most cases.

**Comment by maxandersen** [comment]
@aguibert trick is that you'll need the underlying IDE to support doing that without loading the quarkus or spring plugin to avoid eager loading. Eclipse can do it; not sure if intellij has same ability.

Also, it wouldn't work for empty files :)
