### ISSUE TITLE
Refactor "runAsBackground" to wrap code inside Application.runReadAction()

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/intellij-quarkus#955]
There are plenty of issues with exceptions caused by code not wrapped under Application.runReadAction(). Instead of ad-hoc fixes, we might as well make sure runAsBackground does the wrapping

**Comment by angelozerr** [comment]
I like this idea since IJ Qute/MP side should never write something.

@jeffmaury what do you think about this idea?

I wonder if it is better to use Application.runReadAction() in just some piece of code or if we can use Application.runReadAction() for a big code. Do you think we could have some impact with performance?

**Comment by jeffmaury** [comment]
The reason why I choose not to put it is that it is part of a "generic" language client so there was no reason to assume read was required. But as runAsBackground is already dealing with index building, that's a possible option

**Comment by angelozerr** [comment]
> The reason why I choose not to put it is that it is part of a "generic" language client so there was no reason to assume read was required.

Thanks for your feedback. As we have no usecases which doesn't require read action, I suggest that we use read action in runAsBackground.  Are you OK @jeffmaury ?

**Comment by fbricon** [comment]
you can refactor/rename runAsBackground as runAsBackgroundReadAction, so all the code will be updated, then reintroduce the runAsBackground method, for cases where you don't want the read action
