### ISSUE TITLE
Inaccurate completion in application.properties

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/intellij-quarkus#980]
In application.properties, completion kinda "resets" after the next `.`. Look at `quarkus.vertx.`:

<img width="528" alt="Screenshot 2023-06-28 at 10 29 02" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/934cae87-5e08-4825-a5a6-da1e053c293d">
<img width="587" alt="Screenshot 2023-06-28 at 10 29 17" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/c497ad77-b3b3-476f-bc44-9490fcf732c0">
<img width="714" alt="Screenshot 2023-06-28 at 10 29 34" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/42824454-de5a-4c41-ac9c-0fbec8739b0d">

Compared to VS Code:
<img width="938" alt="Screenshot 2023-06-28 at 10 28 45" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/ef41db71-07e3-4871-a759-2128d06f5a4b">

or IDEA Ultimate's quarkus support:
<img width="535" alt="Screenshot 2023-06-28 at 10 30 18" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/c11a8dee-fe5f-4d58-92f1-c50ff4d15ce9">

**Comment by angelozerr** [comment]
> we need to make LSP4IJ smarter and VS Code like.

We need to do that to avoid having this problem with another ls like lemminx.

**Comment by angelozerr** [comment]
I don't know why, but if you add a new line on the top, it seems it is working:

![image](https://github.com/redhat-developer/intellij-quarkus/assets/1932211/f6ec0e32-b9bf-4187-ab35-346b22556c4f)

**Comment by angelozerr** [comment]
After debugging IJ, it seems IJ doesn't compute correctly the prefix:

 * when file contains only the property, the prefix used for filter completion is empty:
 
```
quarkus.vertx.|
```

it computes prefix by using Java identifier strategy at https://github.com/JetBrains/intellij-community/blob/4afb4f2b8b6f4f03d5703fcb171732454783f319/platform/analysis-impl/src/com/intellij/codeInsight/completion/CompletionData.java#L133

As prefix is empty, it returns all properties.

 * when file contains a blank line space and the property, the prefix used for filter completion is `quarkus.vertx.`:
 
```

quarkus.vertx.|
```

The expected prefix is correct and it is computed from https://github.com/JetBrains/intellij-community/blob/4afb4f2b8b6f4f03d5703fcb171732454783f319/platform/analysis-impl/src/com/intellij/codeInsight/completion/CompletionData.java#L136

I don't know why Ultimate is working, perhaps Ultimate pre-filter the properties that I think it is a bad idea because it should respect the completion filter strategy (camel, etc)
