### ISSUE TITLE
The debug of the plugins runs old version of the IntelliJ Idea

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#99]
When I debug the plugin in newest version of the IntelliJ Idea (on thee img below on the left), the debug starts new instance of IntelliJ Idea, which version is much older (on thee img below on the right). I think it should run the same version (newest if possible) as the instance, in which I am debugging.

![versions](https://user-images.githubusercontent.com/43820055/82153615-d4a7aa00-9868-11ea-95ee-be3fa110bee6.png)

**Comment by jeffmaury** [comment]
This is how the build system based on Gradle is working. The version of IntelliJ used to build and test is set in `gradle.properties`. The value there is the lowest value the plugin support. Because this plugin uses a test infrastructure based on the one from IntelliJ, it is not possible to change it yet (see README)

**Comment by zcervink** [comment]
@jeffmaury I think we can close this issue, because it is not an issue after all - the version of IntelliJ runs correctly according to the gradle.properties file (that I did not know when I was creating this issue).
